SELECT * FROM Sales_Analysis;

-- Count Total Orders
SELECT COUNT(OrderID) AS Total_Orders
FROM Sales_Analysis;

-- Total Revenue
SELECT round(SUM(Quantity * UnitPrice),2) AS Total_Revenue
FROM Sales_Analysis;


-- Average Sales
SELECT Round(avg(Quantity * UnitPrice),2) AS Average_Sales
FROM Sales_Analysis;

-- Determine Revenue Generated by Each Product
SELECT Product,
      round(SUM(Quantity * UnitPrice), 2) AS Revenue
FROM Sales_Analysis
GROUP BY Product
ORDER BY Revenue DESC;

-- Top Performing Products
SELECT Product,
       round(SUM(Quantity * UnitPrice),2) AS Revenue
FROM sales_analysis
GROUP BY Product
ORDER BY Revenue DESC
LIMIT 3;

-- Lowest Performing Product
SELECT Product,
       round(SUM(Quantity * UnitPrice),2) AS Revenue
FROM sales_analysis
GROUP BY Product
ORDER BY Revenue ASC
LIMIT 3;

-- Revenue by Referral Source
SELECT ReferralSource,
       round(SUM(Quantity * UnitPrice),2) AS Revenue
FROM sales_analysis
GROUP BY ReferralSource
ORDER BY Revenue DESC;

-- Order Status Analysis
SELECT OrderStatus,
       COUNT(*) AS Order_Count
FROM sales_analysis
GROUP BY OrderStatus;

-- Monthly Sales Trend
SELECT MONTHNAME(Date) AS Month,
       round(SUM(Quantity * UnitPrice),2) AS Revenue
FROM sales_analysis
GROUP BY MONTHNAME(Date)
ORDER BY Revenue DESC;

-- Yearly Sales Trend
SELECT YEAR(Date) AS Sales_Year,
       round(SUM(Quantity * UnitPrice),2) AS Revenue
FROM sales_analysis
GROUP BY YEAR(Date)
ORDER BY Sales_Year;

-- Top 5 Customers
SELECT CustomerID,
       round(SUM(Quantity * UnitPrice),2) AS Revenue
FROM sales_analysis
GROUP BY CustomerID
ORDER BY Revenue DESC
LIMIT 5;

-- Check for Duplicate Orders
SELECT OrderID,
       COUNT(*) AS Frequency
FROM sales_analysis
GROUP BY OrderID
HAVING COUNT(*) > 1;

-- Check for Repeated Orders
SELECT CustomerID,
       COUNT(*) AS Frequency
FROM sales_analysis
GROUP BY CustomerID
HAVING COUNT(*) > 1;